const RESGISTER_SUCCESS = "REGISTER_SUCCESS";
const RESGISTER_FAIL = "REGISTER_FAIL";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "REGISTER_FAIL";
const LOGOUT = "LOGOUT";

export { RESGISTER_FAIL, RESGISTER_SUCCESS, LOGIN_FAIL, LOGIN_SUCCESS, LOGOUT };
